services:
  api:
    hostname: api
    image: godwin42sh/krampncf:latest
    # build: ./Back
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - PORT=80
      - REDIS_URL=redis://redis:6379
      - SNCF_API_URL=https://api.sncf.com/v1
      - SNCF_API_KEY=
      - SNCF_GTFSRT_URL=https://proxy.transport.data.gouv.fr/resource/sncf-ter-gtfs-rt-trip-updates
  redis:
    hostname: redis
    image: redis:7.4-alpine
    command: ["redis-server", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru"]
